[functions.analyze-weapon-stats]
# Tiempo de espera extendido para procesamiento de IA (m치ximo 300 segundos)
timeout_seconds = 300

# Memoria asignada (m치ximo 8GB para Edge Functions)
memory_mb = 2048

# Variables de entorno requeridas
[functions.analyze-weapon-stats.secrets]
GEMINI_API_KEY = ""
GEMINI_PROJECT_ID = ""

# Configuraci칩n de red
[functions.analyze-weapon-stats.network]
# Permitir conexiones salientes a la API de Google
domains = ["*.googleapis.com"]

# Configuraci칩n de CORS
[functions.analyze-weapon-stats.cors]
allow_origins = ["*"]
allow_methods = ["POST", "OPTIONS"]
allow_headers = ["authorization", "content-type", "x-client-info"]
max_age_seconds = 600
